# Generated by Django 5.1.7 on 2025-03-10 23:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="Label"),
                ),
                (
                    "label_fr",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Label"
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=244, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=244, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=244, null=True, verbose_name="Name"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_fr",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=244, verbose_name="City"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=244, verbose_name="Country"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "exif_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Exif data"
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "photographer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Photographer",
                    ),
                ),
                ("tags", models.ManyToManyField(to="galery.tags")),
            ],
        ),
    ]
