# Generated by Django 5.1.7 on 2025-03-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0003_album_slug_photo_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="tags",
        ),
    ]
