# Generated by Django 5.1.7 on 2025-03-22 22:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0004_remove_photo_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",  # noqa: E501
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
