# Generated by Django 5.1.7 on 2025-04-04 01:56

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0005_photo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=sorl.thumbnail.fields.ImageField(upload_to="photo"),
        ),
    ]
