# Generated by Django 5.1.7 on 2025-04-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0006_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="label",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Label"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
