# Generated by Django 5.1.7 on 2025-04-04 01:56

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0002_alter_user_options_user_date_"
            "joined_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, default="", upload_to="user"
            ),
        ),
    ]
