# Generated by Django 5.1.7 on 2025-04-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("pixelfed", "Pixelfed"),
                            ("facebook", "Facebook"),
                            ("x", "X"),
                            ("mastodpn", "Mastodon"),
                            ("website", "WebSite"),
                            ("flickr", "FlickR"),
                            ("500px", "500px"),
                        ]
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="socials",
            field=models.ManyToManyField(to="user.socials"),
        ),
    ]
