# Generated by Django 5.1.7 on 2025-04-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_socials_user_socials"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="introduction",
            field=models.TextField(blank=True, default=""),
        ),
    ]
